# Generated by Django 5.1.6 on 2025-02-26 15:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Team name')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='useradmin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='userteam', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('remove_member', 'can remove members'), ('remove_admin', 'can remove admin power'), ('add_admin', 'can give admin power')],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Task title')),
                ('desc', models.CharField(max_length=200, verbose_name='Task description')),
                ('start_date', models.DateField(default=datetime.datetime(2025, 2, 26, 21, 12, 39, 88829))),
                ('end_date', models.DateField(default=datetime.datetime(2025, 2, 26, 21, 12, 39, 88878))),
                ('mark_important', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(related_name='usertask', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teams')),
            ],
        ),
    ]
