# Generated by Django 5.1.6 on 2025-02-26 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 45, 18, 356472, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 45, 18, 356420, tzinfo=datetime.timezone.utc)),
        ),
    ]
