# Generated by Django 5.1.6 on 2025-02-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tasks_end_date_alter_tasks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(related_name='usertask', to='home.teams'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 59, 1, 541660, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 59, 1, 541608, tzinfo=datetime.timezone.utc)),
        ),
    ]
