# Generated by Django 5.1.6 on 2025-02-26 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_assigned_to_alter_tasks_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 16, 0, 48, 247979, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 16, 0, 48, 247931, tzinfo=datetime.timezone.utc)),
        ),
    ]
