# Generated by Django 5.1.6 on 2025-02-26 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tasks_end_date_alter_tasks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
