# Generated by Django 5.1.6 on 2025-02-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tasks_end_date_alter_tasks_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'complete'), ('wip', 'work in progress')], default='p', max_length=50),
        ),
    ]
