# Generated by Django 5.1.6 on 2025-02-26 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tasks_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(related_name='usertask', to=settings.AUTH_USER_MODEL),
        ),
    ]
