# Generated by Django 5.1.6 on 2025-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'complete'), ('wip', 'work in progress')], default='pending', max_length=50),
        ),
    ]
