# Generated by Django 5.1.6 on 2025-02-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='code',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
